CREATE DATABASE DUMMYDATA2;
USE DUMMYDATA2;
CREATE TABLE product (
    PRODNO INT PRIMARY KEY,
    PRODNAME VARCHAR(100),
    CATEGORY_ID INT,
    MANUFACTURER VARCHAR(100),
    SUPPLYDATE DATE,
    PRICE DECIMAL(10, 2),
    DISCOUNT DECIMAL(10, 2) DEFAULT NULL,
    STOCK INT
);
show tables;

-- Insert sample data into 'product' table
INSERT INTO product (PRODNO, PRODNAME, CATEGORY_ID, MANUFACTURER, SUPPLYDATE, PRICE, DISCOUNT, STOCK) VALUES
(101, 'Laptop', 1, 'Dell', '2023-01-15', 800.00, 50.00, 200),
(102, 'Smartphone', 1, 'Apple', '2023-03-10', 1000.00, 80.00, 150),
(103, 'Office Chair', 2, 'IKEA', '2022-11-25', 120.00, 15.00, 500),
(104, 'Dining Table', 2, 'Home Depot', '2022-10-12', 350.00, 20.00, 300),
(105, 'Washing Machine', 3, 'Samsung', '2023-02-18', 500.00, 30.00, 100);

 show tables;
 describe PRODUCT;

SELECT PRODNAME FROM PRODUCT WHERE PRODNO='101';
SELECT * FROM PRODUCT WHERE PRICE>500;
SELECT * FROM PRODUCT WHERE PRODNAME='LAPTOP';
SELECT * FROM PRODUCT WHERE SUPPLYDATE>'2023-01-01';
SELECT PRODNAME,PRICE,PRICE*12 FROM PRODUCT WHERE PRICE*12>12000;
SELECT PRODNAME,SUPPLYDATE FROM PRODUCT WHERE SUPPLYDATE<'2023-02-01';
SELECT PRODNAME,PRICE-PRICE*50/100 FROM PRODUCT;
SELECT PRODNAME,PRICE>PRICE*30/100 FROM PRODUCT;
SELECT * from  PRODUCT WHERE SUPPLYDATE <"2023-12-31";
SELECT PRODNAME, PRICE*12  FROM PRODUCT  ;

SELECT PRODNAME,PRICE,PRICE*6 FROM PRODUCT;
SELECT  * , PRICE+2000 FROM PRODUCT ;
SELECT PRODNAME,PRICE,PRICE+PRICE*10/100 FROM PRODUCT;
SELECT PRODNAME,PRICE ,PRICE-PRICE*25/100 FROM PRODUCT;
SELECT PRODNAME,PRICE ,PRICE+PRICE*50/100 FROM PRODUCT ;
SELECT PRICE+DISCOUNT FROM PRODUCT;
SELECT * ,PRICE*12  FROM PRODUCT;
SELECT * FROM PRODUCT WHERE PRODUCT="ELECTRONIC" AND PRICE<500;
SELECT * FROM PRODUCT WHERE PRICE BETWEEN (500 AND 1500) AND DISCOUNT>10.00;
-- Find products whose price is more than 500 and belong to category 3 (Home Appliances).
SELECT * FROM PRODUCT WHERE PRICE<500 AND CATEGORY_ID = 3;


--- 21 Find the product names and prices for products that are either in category 2 (Furniture) or have a price greater than 1000.
SELECT PRODNAME ,PRODNAME  FROM PRODUCT WHERE CATEGORY_ID =2 OR PRICE > 1000;
-- 22.  Find all products with a price greater than 1500 but not belonging to category 3 (Home Appliances).
SELECT *  FROM PRODUCT WHERE PRICE > 1500 AND CATEGORY_ID !=3;
-- 23.  Find the details of products whose price is more than 1500 or their discount is more than 10%.
SELECT * FROM PRODUCT WHERE PRICE >1500 OR DISCOUNT >10;
--- 24.  Find products that have no discount.
SELECT *  FROM PRODUCT WHERE DISCOUNT IS NULL;
-- 25. Find the products with prices between 500 and 1500 and discounts between 5% and 15% using BETWEEN.;
SELECT * FROM PRODUCT WHERE PRICE BETWEEN (500 AND 1500) AND DISCOUNT BETWEEN ( 5 AND 15) 
--  26. Find the products with prices higher than 500 and whose name contains the letter 'L' .
SELECT * FROM PRODUCT WHERE PRICE > 500 AND  PRODNAME LIKE "%L%L%";
-- 27. Find the products with a price greater than 1000, and the product belongs to category 1 (Electronics) and has a discount of 15%.
SELECT * FROM PRODUCT WHERE PRICE>1000 AND CATEGORY_ID = 1 AND DISCOUNT = 15;
-- 28. Find all products whose names end with 'Phone'.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "%PHONE";
-- 29. Find all products whose names contain the word 'Smart'.
SELECT * FROM PRODUCT WHERE NAME LIKE '%SMART%SMART%';
-- 30. Find all products with names that have exactly 5 characters.
SELECT * FROM PRODUCT WHERE NAME LIKE"_____";

-- 31.Find all products with names that have exactly 5 characters.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "_____"
-- Find all products whose names start with 'L' and end with 'X'.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "L%L";
-- 33.Find all products whose names have the letter 'o' in the second position.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "_O%"
-- 34. Find all products whose names start with any character followed by 'P'.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE"_P%";
-- 35. Find all products whose names contain the character 'a' in any position but have 'e' somewhere in the name.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE"%A%A%" AND PRODNAME LIKE"%E%E%";
-- 36.  Find all products whose names start with 'L' and contain 'T' anywhere.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "L%" AND PRODNAME LIKE"%T%T%";
-- 37. Find all products whose names contain 'e' as the third character.\
SELECT * FROM PRODUCT WHERE PRODNAME LIKE"__E%";
-- 38.  Find all products whose names contain 'Ultra' anywhere and end with 'Pro'.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "%ULTRA%ULTRA%" AND PRODNAME LIKE"%PRO";
-- 39. Find all products whose names are 6 characters long and end with 'er'.
SELECT * FROM PRODUCT WHERE PRODNAME '______' AND PRODNAME LIKE "%ER";
-- 40. Find all products whose names contain 'X' as the third character.
SELECT * FROM PRODUCT WHERE PRODNAME LIKE "__X%";

-- ASSIGNEMENT ON MRF( )
-- WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10;

-- WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10.
SELECT COUNT(*) FROM emp
WHERE SAL<2000 AND DEPTNO =10;
-- WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK
SELECT SUM(SAL) FROM EMP WHERE JOB = 'CLERK';
-- WAQTD AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES
SELECT AVG(SAL) FROM EMP ;
-- WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE "A%";
-- WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER
SELECT COUNT(*) FROM EMP WHERE JOB IN('CLERK','MANAGER');
-- WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB
SELECT SUM(SAL) FROM EMP WHERE HIREDATE  LIKE  "____-02-__";
-- WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR)
SELECT COUNT(*) FROM EMP WHERE MGR ='7839';
SELECT * FROM EMP;
-- WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN DEPTNO 30
SELECT COUNT(*) from emp where COMM IS NOT NULL AND DEPTNO = 30;

-- WAQTD AVG SAL , TOTAL SAL , NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDEN
SELECT AVG(SAL),SUM(SAL),COUNT(*),MAX(SAL) FROM EMP WHERE JOB IN ('PRESIDENT');

-- WAQTD NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%A%';
-- WAQTD NUMBER OF EMPS AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L's IN THEIR NAMES
SELECT COUNT(*) ,SUM(SAL) FROM EMP WHERE ENAME LIKE '%LL%';
-- WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DEPTNO) FROM EMP ;

 -- WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES
 SELECT COUNT(*) FROM EMP WHERE 
-- WAQTD NUMBER OF EMPLOYEES HAVING '$' IN THEIR NAMES .
-- WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30
-- WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST
-- WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE
-- WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE
-- WATQD AVG SALARY GIVEN TO THE CLERK
-- WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGEROR A CLERK
-- DIFFRENACE BETWEEN SRF AND MRF
