create database dummydata1;
use dummydata1;


CREATE TABLE emp (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(50),
    JOB VARCHAR(50),
    MGR INT,
    HIREDATE DATE,
    SAL DECIMAL(10, 2),
    COMM DECIMAL(10, 2) DEFAULT NULL,
    DEPTNO INT
);

INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES
(7369, 'SMITH', 'CLERK', 7902, '1980-12-17', 800.00, NULL, 20),
(7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600.00, 300.00, 30),
(7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250.00, 500.00, 30),
(7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975.00, NULL, 20),
(7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250.00, 1400.00, 30),
(7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850.00, NULL, 30),
(7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450.00, NULL, 10),
(7788, 'SCOTT', 'ANALYST', 7566, '1987-04-19', 3000.00, NULL, 20),
(7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000.00, NULL, 10),
(7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500.00, 0.00, 30),
(7876, 'ADAMS', 'CLERK', 7788, '1987-05-23', 1100.00, NULL, 20),
(7900, 'JAMES', 'CLERK', 7698, '1981-12-03', 950.00, NULL, 30),
(7902, 'FORD', 'ANALYST', 7566, '1981-12-03', 3000.00, NULL, 20),
(7934, 'MILLER', 'CLERK', 7782, '1982-01-23', 1300.00, NULL, 10);


CREATE TABLE dept (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON');


CREATE TABLE salgrade (
    GRADE INT PRIMARY KEY,
    LOSAL INT,
    HISAL INT
);
SELECT * FROM DEPT;
USE DUMMYDATA1;




--  ASSIGNMENT ON CASE 2 :
-- 1.WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH
SELECT DNAME FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');
-- 2.WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING
SELECT DNAME FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='king');
-- 3.WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=7902);
-- 4.WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R' .
SELECT DNAME,LOC,DEPTNO FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME LIKE "%R");
-- 5.WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE JOB ='PRESIDENT');
-- 6.WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT DNAME FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE JOB='ACCOUNTING');
-- 7.WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE  LOCATION CHICAGO
SELECT ENAME,SAL FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');
-- 8.WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES
SELECT * FROM dept WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE JOB='SALES');
-- 9.WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEESARE WORKING IN NEW YORK
SELECT * ,SAL*12 AS ANNUAL_SAL FROM EMP  WHERE DEPTNO =(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
-- 10. WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME  FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');
-- ASSIGNMENT ON CASE 1 & 2
-- 1.WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SCOTT' AND (SELECT DEPTNO FROM DEPT WHERE  DNAME='ACCOUNTING'));
-- 2.WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO
SELECT * FROM EMP WHERE JOB='MANAGER'AND DEPTNO IN( SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');
-- 3.WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME,SAL FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME ='KING' AND DEPTNO IN (SELECT DEPTNO FROM  DEPT WHERE JOB = 'ACCOUNTIG'));
-- 4.WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES
SELECT * FROM EMP WHERE JOB='SALESMAN' AND DEPTNO IN (SELECT DEPTNO  FROM DEPT WHERE DNAME='SALES');
-- 5.WAQTD NAME , SAL , JOB , HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME,SAL,JOB,HIREDATE FROM  EMP WHERE DNAME IN (SELECT DNAME FROM DEPT WHERE DNAME='OPERATIONS' AND DEPTNO =(SELECT DEPTNO  FROM EMP WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='KING')));
-- 6.DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE'%S');
-- 7.WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT .
-- 8.WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800 .
-- 9.WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
-- 10.WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 
FROM EMP,DEPT 
WHERE EMP.DEPTNO=DEPT.DEPTNO;


SELECT * FROM EMP,DEPT 
 WHERE EMP.DEPTNO=DEPT.DEPTNO;
 
-- assigmant
select ename,loc from emp,dept;

SELECT DNAME,SAL FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='ACCOUNTING';
SELECT DNAME,SAL*12 FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>2340;
SELECT ENAME,DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME LIKE '%A%';
SELECT ENAME,DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND  JOB='SALESMAN';
SELECT DNAME,JOB FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME AND  ENAME LIKE'S%';
SELECT DNAME,MGR  FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND MGR=7839;
SELECT DNAME,HIREDATE FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND HIREDATE>'1983-12-31' AND JOB = 'ACCOUNTING' OR DNAME ='RESEARCH';
SELECT DNAME,ENAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND COMM IS  NOT NULL AND DEPTNO IN (10,30);
SELECT DNAME,EMPNO FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND EMPNO IN (7839,7902) AND LOC='NEW YORK';


-- ASSIGNMENT ON EMP AND MANAGER RELATION




SELECT E1.ENAME,E2.ENAME AS MANAGER FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB="CLERK";
SELECT E1.ENAME,E2.ENAME AS MANAGER FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E2.JOB="MANAGER" AND E2.DEPTNO IN (10,20);
SELECT E1.ENAME,E1.SAL,E2.ENAME AS MGR,E2.SAL FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.SAL>2300 AND E2.SAL>2300;
SELECT E1.ENAME ,E2.ENAME AS MANAGER,E2.HIREDATE AS MGR_HDATE FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E2.HIREDATE<'1982-01-01';
    SELECT E1.ENAME,E2.ENAME AS MGR ,E2.COMM  FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB='SALESMAN' AND E2.DEPTNO=30;
SELECT E1.ENAME,E1.SAL,E2.ENAME AS MGR ,E2.SAL FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.SAL>E2.SAL;
SELECT E1.ENAME ,E1.HIREDATE,E2.ENAME AS MANAGER,E2.HIREDATE AS MGR_HDATE FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E2.HIREDATE<E1.HIREDATE;
SELECT E1.ENAME,E1.JOB,E2.ENAME AS MGR ,E2.JOB  FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB=E2.JOB ;
SELECT E1.ENAME,E2.ENAME AS MGR ,E2.JOB  FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E2.JOB='MANAGER' ;
SELECT E1.ENAME,E1.SAL*12  AS ANNUALSAL ,E2.ENAME AS MGR ,E2.SAL*12 AS ANNUALSAL,E1.DEPTNO ,E1.SAL,E2.SAL AS MGRSAL FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO IN (10, 20) AND E2.SAL>E1.SAL;
SELECT E1.ENAME,E2.JOB,E2.ENAME AS MGR   FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO ;
SELECT E1.ENAME,E2.ENAME AS MGR ,E2.SAL  FROM EMP AS E1,EMP AS E2 WHERE E1.MGR=E2.EMPNO AND E2.SAL LIKE  "%50.00" ;

SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='SMITH');
-- WAQTD ADAMS MANAGER'S MANAGER NAME?
SELECT ENAME FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ADAMS'));
-- WAQTD DNAME OF JONES MANAGER?
SELECT DNAME FROM DEPT WHERE  DNAME=(SELECT DEPTNO FROM DEPT WHERE EMPNO =(SELECT MGR FROM EMP WHERE ENAME="JONES") );

-- WAQTD MILLER'S MANAGER'S SALARY?
SELECT ENAME,SAL from emp where EMPNO=(SELECT MGR FROM EMP WHERE ENAME='MILLER');
-- WAQTD LOC OF SMITH'S MANAGER'S MANAGER?
SELECT LOC,ENAME FROM EMP,DEPT  WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH')); 
-- WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE?
SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='BLAKE');
-- WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING?
SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');
-- WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES?
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME="JONES");
-- WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S .MANAGER?
SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='BLAKE'));
-- WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER?
SELECT COUNT(*) FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='FORD'));