create database EMP;
use emp;
select * from emp;
show databases;
use emp;
show tables;
describe emp;
drop database emp;



create table EMP( EMPNO int primary key,EName varchar(300),Job varchar(300),HIREDATE date,MGR int,SAL int,COMM int,DEPTNO int);
show tables;
insert into EMP(EMPNO,EName,Job,HIREDATE,MGR,SAL,COMM,DEPTNO) values
(7369,"SMITH","CLERK","1980-12-17","7902","800",null,"20"),
(7499,"ALLEN","SALESMAN","1981-02-20","7698","1600","300","30"),
(7521,"WARD","SALESMAN","1981-02-22","7698","1250","500","30"),
(7566,"JONES","MANAGER","1981-04-02","7839","2975",null,"20"),
(7654,"MARTIN","SALESMAN","1981-09-28","7698","1250","1400","30"),
(7698,"BLAKE","MANAGER","1981-05-01","7839","2850",null,"30"),
(7782,"CLARK","MANAGER","1981-06-09","7839","2450",null,"10"),
(7788,"SCOTT","ANALYST","1987-04-19","7566","3000",null,"20"),
(7839,"KING","PRESIDENT","1981-11-17",null,"5000",null,"10"),
(7844,"TURNER","SALESMAN","1981-09-08","7698","1500","0","30"),
(7876,"ADAMS","CLERK","1987-05-23","7788","1100",null,"20"),
(7900,"JAMES","CLERK","1981-12-03","7698","950",null,"30"),
(7902,"FORD","ANALYST","1981-12-03","7566","3000",null,"20"),
(7934,"MILLER","CLERK","1981-01-23","7782","1300",null,"10");
select*from EMP;
show tables;
#1. Table  Employees
CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    PhoneNumber VARCHAR(15),
    HireDate DATE,
    Salary DECIMAL(10, 2)
);
describe emp3;
#2. Table  Products
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(8, 2),
    StockQuantity INT,
    SupplierID INT,
    Description TEXT
);

#3. Table  Orders
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    OrderDate DATE,
    ShippingAddress VARCHAR(200),
    TotalAmount DECIMAL(10, 2),
    PaymentMethod VARCHAR(50),
    Status VARCHAR(20)
);

#4. Table  Students
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    DateOfBirth DATE,
    GradeLevel INT,
    Email VARCHAR(100),
    PhoneNumber VARCHAR(15)
);

#5. Table  Courses
CREATE TABLE Courses (
    CourseID INT PRIMARY KEY,
    CourseName VARCHAR(100),
    Department VARCHAR(50),
    Credits INT,
    Instructor VARCHAR(100),
    Schedule VARCHAR(50),
    EnrollmentLimit INT
);

#6. Table  Books
CREATE TABLE Books (
    BookID INT PRIMARY KEY,
    Title VARCHAR(200),
    Author VARCHAR(100),
    Genre VARCHAR(50),
    PublishedYear INT,
    ISBN VARCHAR(20),
    Price DECIMAL(8, 2)
);

#7. Table  Flights
CREATE TABLE Flights (
    FlightID INT PRIMARY KEY,
    Airline VARCHAR(100),
    DepartureCity VARCHAR(50),
    ArrivalCity VARCHAR(50),
    DepartureTime DATETIME,
    ArrivalTime DATETIME,
    Price DECIMAL(10, 2)
);

#8. Table  Hotels
CREATE TABLE Hotels (
    HotelID INT PRIMARY KEY,
    HotelName VARCHAR(100),
    City VARCHAR(50),
    Stars INT,
    TotalRooms INT,
    AvailableRooms INT,
    PricePerNight DECIMAL(10, 2)
);

#9. Table  Vehicles
CREATE TABLE Vehicles (
    VehicleID INT PRIMARY KEY,
    Make VARCHAR(50),
    Model VARCHAR(50),
    Year INT,
    Color VARCHAR(30),
    LicensePlate VARCHAR(20),
    OwnerID INT
);

#10. Table Payments
CREATE TABLE Payments (
    PaymentID INT PRIMARY KEY,
    CustomerID INT,
    PaymentDate DATE,
    Amount DECIMAL(10, 2),
    PaymentType VARCHAR(50),
    TransactionID VARCHAR(50),
    Status VARCHAR(20)
);

#1. WRITE A QUERY TO DISPLAY ALL THE DETAILS FROM THE EMPLOYEE TABLE.
SELECT * FROM EMP;
#2. WAQTD NAMES OF ALL THE EMPLOYEES.
SELECT ENAME FROM EMP;
#3. WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME , SAL FROM EMP;
#4. WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME,COMM FROM EMP;
#5. WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES IN EMP TABLE.
SELECT EMPNO , DEPTNO FROM EMP;
#6. WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES .
SELECT ENAME,HIREDATE FROM EMP;
#7. WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES .
SELECT ENAME , JOB FROM EMP;
#8. WAQTD NAME , JOB AND SALARY GIVEN ALL THE EMPLOYEES.
SELECT ENAME,JOB FROM EMP;
#9. WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.
SELECT DNAME,DEPTNO FROM DEPT;
#10. WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.



#1) WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.
SELECT ENAME,SAL*12  ANNUAL_SAL FROM EMP;
#2) WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH THEIR HALF TERM SALARY.
SELECT ENAME,JOB,SAL*6  ANNUAL_SAL FROM EMP;
#3)WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH AN ANNUALBONUS OF 2000.
SELECT ENAME,EMPNO,DEPTNO,JOB,COMM,MGR,HIREDATE,SAL+2000 FROM EMP;
#4) WAQTD NAME SALARY AND SALARY WITH A HIKE OF 10%.
SELECT ENAME,SAL+SAL*10/100 FROM EMP;
#5) WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.
SELECT ENAME,SAL-SAL*25/100 FROM EMP;
#6) WAQTD NAME AND SALARY WITH MONTHLY HIKE OF 50%.
SELECT ENAME,SAL+SAL*50/100 FROM EMP;
#7) WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10%.
SELECT ENAME,SAL-SAL*10/100 FROM EMP;
#8) WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COMM).
SELECT SAL+COMM  FROM EMP;
#9) WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY.
SELECT * ,SAL*12  ANNUAL_SAL FROM EMP;
#10) WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY. 
SELECT ENAME,SAL-100  FROM EMP;



#1. WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOSE NAME IS SMITH
SELECT SAL * 12 AS ANNUAL_SALARY
FROM EMP
WHERE ENAME = 'SMITH';
#2. WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK
SELECT ENAME
FROM EMP
WHERE JOB = 'CLERK';
#3. WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN

SELECT ENAME, SAL
FROM EMP
WHERE JOB = 'SALESMAN';
#4. WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000
SELECT *
FROM EMP
WHERE SAL > 2000;
#5. WAQTD DETAILS OF THE EMP WHOSE NAME IS JONES
SELECT *
FROM EMP
WHERE ENAME = 'JONES';
#6. WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81
SELECT *
FROM EMP
WHERE HIREDATE > ('1981-01-01');
#7. WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000

SELECT ENAME, SAL, SAL * 12 AS ANNUAL_SALARY
FROM EMP
WHERE SAL * 12 > 12000;
#8. WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30

SELECT EMPNO
FROM EMP
WHERE DEPTNO = 30;
#9. WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981

SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < ('1981-01-01');
#10. WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER

SELECT *
FROM EMP
WHERE JOB = 'MANAGER';
#11. WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400

SELECT ENAME, SAL
FROM EMP
WHERE COMM = 1400;
#12. WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY

SELECT *
FROM EMP
WHERE COMM > SAL;
#13. WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87

SELECT EMPNO
FROM EMP
WHERE HIREDATE < 1987-01-01;
#14. WAQTD DETAILS OF EMPLOYEES WORKING AS AN ANALYST

SELECT *
FROM EMP
WHERE JOB = 'ANALYST';
#15. WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 2000 RUPEES PER MONTH

SELECT *
FROM EMP
WHERE SAL > 2000;
    
    
    
    
#WAQTD DETAILS OF THE EMPLOYEE WORKING AS CLERK AND EARNING LESS THEN 1500
  SELECT * FROM EMP 
  WHERE JOB='CLERK' AND SAL>1500;
  
  
SELECT ENAME,HIREDATE  FROM EMP
WHERE JOB="MANAGER" AND DEPTNO = 30;
  
SELECT * ,SAL*12 AS ANNUAL_SALARY FROM EMP 
WHERE DEPTNO=30 AND JOB="SALESMAN" AND SAL*12 >14000;

SELECT * FROM EMP
WHERE DEPTNO=30 OR JOB='ANALYST';

SELECT ENAME FROM EMP
WHERE SAL>1100 AND JOB='CLERK';

SELECT ENAME,SAL,SAL*12 AS ANNUAL_SALARY FROM emp
WHERE DEPTNO=20 AND SAL=1100 AND SAL*12 > 12000;

SELECT EMPNO,ENAME FROM emp
WHERE JOB="MANAGER" AND DEPTNO = 20;
 
 
 SELECT * FROM EMP
 WHERE DEPTNO=20 AND DEPTNO=30;
 
 SELECT * FROM EMP
 WHERE JOB="ANALYST" AND DEPTNO=10;
 
 SELECT *  FROM EMP
 WHERE J
 OB="PRESIDENT" AND SAL=4000 ;
 
 SELECT ENAME,DEPTNO,JOB FROM EMP 
 WHERE JOB="CLERK" AND DEPTNO= 10 OR DEPTNO= 20;
 
 SELECT * FROM EMP
  WHERE JOB = 'CLERK' OR JOB='MANAGER' OR JOB= 'SALESMAN' OR JOB='CLERK';
  
  SELECT ENAME FROM EMP
  WHERE DEPTNO =10 OR DEPTNO=20 OR DEPTNO =30 OR DEPTNO =40;
  
  SELECT * FROM EMP
  WHERE EMPNO =7902 AND EMPNO=7839;
  
SELECT * FROM EMP
WHERE JOB='MANAGER' OR JOB='SALESMAN' OR JOB='CLERK';

SELECT ENAME,HIREDATE FROM EMP
WHERE HIREDATE >"1981-12-31"  AND HIREDATE<"1987-01-01";

SELECT * FROM EMP
WHERE SAL>1250 AND SAL<3000;

SELECT ENAME  FROM EMP
 WHERE HIREDATE >"1981-12-31" AND DEPTNO=10 OR DEPTNO=30;
  
 SELECT ENAME,SAL*12 AS ANNUAL_SALARY  FROM EMP
 WHERE JOB='MANAGER' OR JOB='CLERK' AND DEPTNO =10 OR DEPTNO =20 OR DEPTNO =30;
 
 SELECT * FROM EMP 
 WHERE SAL >1000 AND SAL<4000 AND SAL*12>15000;


#1) WAQTD NAMES AND DEPTNO , JOB OF EMPS WORKING AS CLERK IN DEPT 10 OR 20
SELECT ENAME,DEPTNO,JOB FROM EMP
WHERE JOB='CLERK' AND DEPTNO =10 OR DEPTNO=20;

#2)WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPT 10 AND EARNING SAL MORE THAN 1250 .
SELECT * FROM emp
WHERE JOB='CLERK' AND DEPTNO=10 AND SAL>1250;
#3) WAQTD NAMES OF EMPLOYEES WORKING IN DEPT 10 ,20 , 30 , 40 AS A CLERK
SELECT  ENAME FROM EMP 
WHERE DEPTNO =10 OR DEPTNO=20 OR DEPTNO =30 OR DEPTNO=40 AND JOB = 'CLERK';
#4) WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839 IN DEPT 10 OR 30
SELECT * FROM EMP
 WHERE EMPNO=7902 AND EMPNO=7839 AND DEPTNO=10 OR DEPTNO=30;
#5) WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK IN DEPT 40
SELECT * FROM EMP
WHERE JOB="MANAGER" OR JOB="CLERK" AND DEPTNO=40;
#6) WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87 AS A PRESIDENT
SELECT ENAME FROM EMP
WHERE HIREDATE>'1981-12-31' AND HIREDATE< "1987-01-01" AND JOB = 'PRESIDENT';
#7) WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000
SELECT * FROM emp
WHERE SAL>1250 AND SAL<3000;
#9) WAQTD NAMES OF EMPLOYEES HIRED AFTER 2020 INTO DEPT 10 OR 30
SELECT NAME FROM EMP
WHERE HIREDATE >"2020-01-01" AND DEPTNO =10 OR DEPTNO=30;

#10) WAQTD NAMES OF EMPLOYEES WITH SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30
SELECT ENAME FROM emp WHERE JOB ='MANAGER' OR JOB='CLERK' AND DEPTNO =10 OR DEPTNO=30;
#11) WAQTD ALL THE DETAILS IDSAL IS BETWEEN 1000 AND 4000 IN DEPT 10 OR 20 AND WORKING AS A MANAGER OR ANALYST

SELECT * FROM emp WHERE SAL<1000 AND SAL >4000 AND DEPTNO=10 OR DEPTNO =20 AND JOB= 'MANAGER' OR JOB ='ANALYST';


#1) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
SELECT * FROM EMP 
WHERE COMM IS NULL;
#2) LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER
SELECT * FROM EMP 
WHERE JOB NOT IN ("MANAGER");
#3) LIST ALL THE SALESMEN IN DEPT 30
SELECT * FROM EMP  
WHERE JOB IN ("SALESMAN") AND DEPTNO = 30;
#4) LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500
SELECT * FROM EMP 
WHERE JOB IN ('SALESMAN') AND DEPTNO=30 AND SAL >1500;
#5) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘S’ OR ‘A’
SELECT * FROM EMP 
WHERE ENAME LIKE "S%" OR ENAME LIKE "A%";
#6) LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT * FROM EMP 
WHERE DEPTNO NOT IN (10,20);
#7) LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH ‘S’
SELECT * FROM EMP 
WHERE ENAME NOT LIKE "S%";
#8) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10
SELECT * FROM EMP 
WHERE JOB IN ('MANAGER') AND DEPTNO =10;
#9) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK
SELECT * FROM EMP
WHERE COMM IS NULL AND JOB IN ("CLERK");
#10) LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30
SELECT * FROM EMP 
WHERE JOB NOT IN ("MANAGER") AND DEPTNO IN(10,30);


#11) LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
SELECT * FROM emp
 WHERE JOB IN ("SALESMAN") AND DEPTNO =30 AND SAL>2450;
#12) LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500
SELECT * FROM EMP 
WHERE JOB IN("ANALYST") AND DEPTNO =20 AND SAL>2500;
#13) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘M’ OR ‘J’
SELECT * FROM EMP
WHERE ENAME LIKE "M%" OR ENAME LIKE "J%" ;
#14) LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30
SELECT * ,SAl*12 AS ANNUAL_SAL FROM EMP WHERE DEPTNO NOT IN (30);

#15) LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ‘ES’ OR ‘R’
SELECT * FROM EMP 
WHERE ENAME NOT LIKE '%ES' OR  ENAME NOT LIKE '%R';
#17) DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE CHARACTER IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER
SELECT * FROM EMP
WHERE JOB IN ('SALESMAN') AND ENAME LIKE "%E" AND SAL"____";
#18) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81
SELECT * FROM EMP WHERE HIREDATE > '1981-12-31';
#19) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB
SELECT * FROM emp  
WHERE HIREDATE IN ("%-02-%");
#20) LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000
SELECT * FROM EMP 
WHERE JOB NOT IN ("MANAGER","CLERK") AND DEPTNO IN (10,20) AND SAL   BETWEEN(1000,3000);


#ASSIGNMENT ON MMRF():
SELECT COUNT(*) FROM EMP WHERE SAL<2000 AND DEPTNO=10;
SELECT SUM(SAL) FROM EMP WHERE JOB='CLERK';
SELECT  AVG(SAL) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE 'A%';
SELECT COUNT(*) FROM EMP WHERE JOB IN ('CLERK','MANAGER');
SELECT SUM(SAL) FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE) ='02';
SELECT COUNT(*) FROM EMP WHERE MGR='7839';
SELECT COUNT(*) FROM EMP WHERE COMM IS NOT NULL AND DEPTNO=30;
SELECT AVG(SAL),SUM(SAL),COUNT(*),MAX(SAL) FROM EMP WHERE JOB='PRESIDENT';
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%A%';
SELECT COUNT(*),SUM(SAL) FROM EMP WHERE ENAME LIKE '%LL%';
SELECT COUNT(*) FROM EMP DEPTNO;
SELECT COUNT(*) FROM EMP WHERE ENAME  LIKE '%Z%' ;
SELECT COUNT(*) FROM EMP WHERE ENAME  LIKE '%$%' ;
SELECT SUM(SAL) FROM EMP WHERE JOB='CLERK' AND DEPTNO=30; 
SELECT MAX(SAL)  FROM EMP WHERE JOB='ANALYST';
SELECT COUNT(DISTINCT SAL) FROM EMP;
SELECT COUNT(JOB) FROM EMP;
SELECT AVG(SAL) FROM EMP WHERE JOB='CLERK';
SELECT MIN(SAL) FROM EMP
 WHERE DEPTNO=10  AND JOB='MANAGER'OR ENAME='CLERK';
 
--  WAQTD NUMBEROF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
SELECT COUNT(*) FROM emp
WHERE JOB NOT LIKE "PRESIDENT"
GROUP BY DEPTNO;
-- WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
SELECT SUM(SAL) FROM EMP 
GROUP BY JOB;
-- WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT .
SELECT COUNT(*) FROM EMP 
WHERE JOB = "MANAGER" 
GROUP BY DEPTNO;
-- WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20.
SELECT AVG(SAL) FROM EMP 
WHERE DEPTNO NOT LIKE "20"
GROUP BY DEPTNO;
-- WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB .
SELECT COUNT(*),JOB FROM EMP 
WHERE ENAME LIKE "%A%"
GROUP BY JOB;
-- WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
SELECT COUNT(*),AVG(SAL) FROM EMP  WHERE SAL >2000  GROUP BY DEPTNO;
-- WAQTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT.
SELECT SUM(SAL),COUNT(*) FROM EMP WHERE JOB = "SALESMAN" GROUP BY DEPTNO;
-- WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
SELECT COUNT(*) ,MAX(SAL) FROM EMP GROUP BY JOB;
-- WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO;
-- WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE .
SELECT COUNT(SAL) FROM EMP GROUP BY SAL;


--  WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST ;
SELECT DEPTNO,COUNT(),job FROM EMP  WHERE job="CLERK" GROUP BY DEPTNO HAVING COUNT()>=2;
SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=4;
SELECT COUNT(*),SUM(SAL),JOB FROM EMP WHERE SAL>1200 GROUP BY JOB HAVING SUM(SAL)>3800;
SELECT DEPTNO,COUNT() FROM EMP WHERE JOB="MANAGER" GROUP BY DEPTNO HAVING COUNT()=2;
SELECT JOB,MAX(SAL) FROM EMP GROUP BY JOB HAVING MAX(SAL)>2600;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(*)>1;
SELECT HIREDATE FROM EMP GROUP BY HIREDATE HAVING COUNT(*) >1;
SELECT AVG(SAL),DEPTNO FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)<3000;
SELECT DEPTNO FROM EMP WHERE ENAME LIKE "%A%" OR ENAME LIKE "%S%" GROUP BY DEPTNO HAVING COUNT(*)>=3;
SELECT MIN(SAL),MAX(SAL),JOB FROM EMP GROUP BY JOB HAVING MIN(SAL)>1000 AND MAX(SAL)<5000;
SELECT JOB,SUM(SAL) FROM EMP GROUP BY JOB HAVING SUM(SAL)>3450;
SELECT JOB,SUM(SAL) FROM EMP WHERE SAL>1500 GROUP BY JOB;
SELECT JOB,MAX(SAL) FROM EMP GROUP BY JOB HAVING  MAX(SAL)>2000;

 
--  1) WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS;
SELECT ENAME FROM EMP  WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME="ADAMS");

-- 2) WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME FROM EMP WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME="KING");
-- 3) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME ,DEPTNO FROM EMP WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME="JONES");

-- 4) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES
SELECT ENAME,JOB FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME="JAMES");
-- 5) WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THEEMPLOYEES IF THEIR ANNUAL  SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT ENAME,EMPNO,SAL*12 AS ANNUAL_SAL FROM EMP WHERE ENAME>(SELECT ENAME FROM EMP WHERE ENAME="WARDS");

-- 7) WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT
 SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT');

-- 8) WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME='PRESIDENT');
-- 9) WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME,SAL FROM EMP WHERE SAL< (SELECT SAL FROM EMP WHERE EMPNO=7839);

-- 10) WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER
SELECT * FROM EMP WHERE HIREDATE >(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');
-- 11) WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME,SAL FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='ALLEN');
-- 12) WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN 
SELECT ENAME,SAL FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='MILLER') AND SAL <( SELECT SAL FROM EMP WHERE ENAME='ALLEN');
-- 13) WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH'
SELECT * FROM EMP WHERE DEPTNO=20 AND JOB=(SELECT JOB FROM EMP WHERE ENAME = 'SMITH');
14) WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER;
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO =(SELECT JOB FROM EMP WHERE ENAME ='TURNER');


15) WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING
SELECT ENAME FROM EMP WHERE HIREDATE >'1980-01-01' AND HIREDATE <((SELECT HIREDATE FROM EMP WHERE ENAME ='KING');
SELECT HIREDATE FROM EMP WHERE ENAME ='KING';
SELECT ENAME FROM EMP WHERE HIREDATE < '1980-01-01';
-- 16) WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500;


SELECT  ENAME,SAL*12 AS ANNUAL_SAL FROM EMP WHERE SAL > 3500 AND SAL< (SELECT SAL FROM EMP WHERE ENAME='BLAKE');
17) WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING;
 SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');

18) WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE;

SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');
-- 19) WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH;
SELECT ENAME ,COMM FROM EMP WHERE COMM IS NOT NULL AND JOB = (SELECT JOB FROM EMP WHERE ENAME ='SMITH');
-- 20) WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER .
SELECT * FROM EMP WHERE JOB = 'CLERK' AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

-- 21) WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES;
SELECT ENAME,SAL,JOB FROM EMP;
-- 22) WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.;
SELECT SAL*12 AS ANNUAL_SAL  FROM EMP WHERE SAL >  (SELECT SAL FROM EMP WHERE ENAME='SMITH' ) AND SAL < (SELECT  SAL FROM EMP WHERE ENAME ='KING');
-- 23) WAQTD names of the employees earning more than 2500 .
SELECT ENAME FROM EMP WHERE SAL>2500;
-- 24) WAQTD names of the employees earning less than MILLER .
SELECT ENAME FROM EMP WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME ='MILLER');
-- 25) WAQTD name and deptno of the employees working in the same Dept as SMITH .
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');
-- 26) WAQTD name and hiredate of the employees if the employee Was hired after JONES .

SELECT ENAME,HIREDATE FROM  EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME="JONES");
-- 27) WAQTD all the details of the employee working in the same Designation as KING .
SELECT * FROM EMP WHERE JOB=( SELECT JOB FROM EMP WHERE ENAME="KING");
-- 28) WAQTD name , sal , deptno of the employees if the employees Earn more than 2000 and work in the same dept as JAMES .;
SELECT ENAME,SAL,DEPTNO FROM EMP WHERE SAL>2000 AND DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME="JAMES");
-- 29) WAQTD all the details of the employees working in the Same designation as MILLER and earning more than 1500.;
SELECT * FROM EMP WHERE SAL> 1500 AND JOB=( SELECT JOB FROM EMP WHERE ENAME='MILLER');
-- 30) WAQTD details of the employees earning more than SMITH But less than KING .
SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME="SMITH") AND SAL< (SELECT SAL FROM EMP WHERE ENAME='KING');
-- 31) WAQTD name , sal and deptno of the employees if the employee Is earning commission in dept 20 and earning salary more than Scott .
SELECT ENAME,SAL,DEPTNO FROM EMP WHERE COMM IS NOT NULL AND DEPTNO=20 AND SAL> ( SELECT SAL FROM EMP WHERE ENAME ="SCOTT");
-- 32) WAQTD name and hiredate of the employees whose name ends with 'S' and hired after James .
SELECT ENAME,HIREDATE FROM EMP WHERE ENAME LIKE 'S%' AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME='JAMES');+
-- 33) WAQTD names of the employees working in the same dept as JAMES and earning salary more than ADAMSand working in the same job role as MILLER and hired after MARTIN .
-- 34) WAQTD all the details of the employees working as salesman in the dept 20 and earning commission more than Smith and hired after KING .
-- -35) WAQTD number of employees earning more than SMITH and less than MARTIN .
-- 36) WAQTD Ename and SAL for all the employees earning more than JONES
 
 